services:
  webapp:
    image: pasinduljay/sharepoint-downloader:1.0
    container_name: sharepoint-downloader
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Add any additional required environment variables here
    volumes:
      - ./downloads:/downloads
    networks:
      - reverse-proxy
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000 # Change as per your user ID
      - PGID=1000 # Change as per your group ID
      - TZ=Etc/UTC
    volumes:
      - ./downloads:/srv
    networks:
      - reverse-proxy
    restart: unless-stopped

  nginx-proxy-manager:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx/reverse-proxy:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl/
    ports:
      - '80:80'   # HTTP
      - '443:443' # HTTPS
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    driver: bridge
    name: SPNetwork    
  