name: Sharepoint Downloader

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
      INSTANCE_USERNAME: ${{ secrets.INSTANCE_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      SSL_CERT: ${{ secrets.SSL_CERT }}
      SSL_KEY: ${{ secrets.SSL_KEY }}

    steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy webapp
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ${{ env.INSTANCE_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          # Stop existing containers
          cd /home/ubuntu/Sharepoint-Video-Downloader || true
          sudo docker-compose down -v || true
          
          # Clean up existing directory with proper permissions
          cd /home/ubuntu
          sudo rm -rf Sharepoint-Video-Downloader
          git clone https://${{ env.GITHUB_USERNAME }}:${{ env.GITHUB_TOKEN }}@github.com/pasinduljay/Sharepoint-Video-Downloader.git
          cd Sharepoint-Video-Downloader
          
          # Create SSL certificate and key files from GitHub Secrets
          mkdir -p ./nginx/ssl
          echo "${{ env.SSL_CERT }}" > ./nginx/ssl/cloudflare.crt
          echo "${{ env.SSL_KEY }}" > ./nginx/ssl/cloudflare.key

          # Install/update Docker if needed
          bash <(curl -Ls https://gist.githubusercontent.com/pasinduljay/02cf2effb83c771c6f302b2ba59faf74/raw/8f1a8903b11da98510bb53f452fd8a0b35f04c53/Verification%2520for%2520Docker%2520and%2520Docker-compose)
          
          # Deploy containers
          sudo docker-compose pull
          sudo docker-compose up -d